In [6]:
import numpy as np

In [1]:
mylist = [i for i in range(10)]
type(mylist)

list

In [2]:
mylist*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
myarra = np.array(mylist)
type(myarra)

numpy.ndarray

In [8]:
myarra**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
mymatrix = np.array([[0,1,5],[2,3,4],[3,6,7],[8,9,10,]])
mymatrix

array([[ 0,  1,  5],
       [ 2,  3,  4],
       [ 3,  6,  7],
       [ 8,  9, 10]])

In [11]:
mymatrix[:,0:1]

array([[0],
       [2],
       [3],
       [8]])

In [12]:
mymatrix[:,1:2]

array([[1],
       [3],
       [6],
       [9]])

In [14]:
mymatrix[:,2:3]

array([[ 5],
       [ 4],
       [ 7],
       [10]])

In [15]:
mymatrix[:,1:3]

array([[ 1,  5],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])

In [16]:
mymatrix[0:2,1:2]

array([[1],
       [3]])

In [17]:
mymatrix[0:2,2:3]

array([[5],
       [4]])

In [18]:
mymatrix[:,:]

array([[ 0,  1,  5],
       [ 2,  3,  4],
       [ 3,  6,  7],
       [ 8,  9, 10]])

In [19]:
mymatrix[0:3,0:3]

array([[0, 1, 5],
       [2, 3, 4],
       [3, 6, 7]])

In [22]:
myrange = np.arange(10)
myrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

NameError: name 'myarange' is not defined

In [24]:
myrangestep = np.arange(0,10,2)
myrangestep

array([0, 2, 4, 6, 8])

* zeros and ones

In [26]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
t = np.zeros(4)
t

array([0., 0., 0., 0.])

In [30]:
O1 = np.ones(5)
O1

array([1., 1., 1., 1., 1.])

In [32]:
O6 = np.ones((6,6))
O6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# linspace

In [37]:
L = np.linspace(1,25,9)
L

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25.])

In [38]:
L3 = L.reshape(3,3)
L3

array([[ 1.,  4.,  7.],
       [10., 13., 16.],
       [19., 22., 25.]])

# eye

In [39]:
I2 = np.eye(2)
I2

array([[1., 0.],
       [0., 1.]])

In [40]:
I4 = np.eye(4)
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
I43 = np.eye(4,3)
I43

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [42]:
I43[0:2,0:2]

array([[1., 0.],
       [0., 1.]])

# Random

In [43]:
import random

In [44]:
arr = np.random.rand(3,4)
arr

array([[0.03632354, 0.28648553, 0.52222419, 0.56068203],
       [0.69891979, 0.12541996, 0.78807316, 0.22717524],
       [0.2361706 , 0.18200655, 0.56135613, 0.47935114]])

In [45]:
from numpy.random import rand

In [46]:
arr_simple = rand(3,4)
arr_simple

array([[0.1804995 , 0.75236799, 0.11804418, 0.02885145],
       [0.46239081, 0.02500754, 0.98449502, 0.06858232],
       [0.1146403 , 0.33993582, 0.83375846, 0.41693133]])

# randn

In [48]:
from numpy.random import randn

In [49]:
mat = randn(3,2)
mat

array([[ 0.9683006 , -0.83674952],
       [-0.4014191 ,  0.85532765],
       [ 2.41197889, -0.16999162]])

In [50]:
# lambda
seq = [i for i in range(5)]
seq

[0, 1, 2, 3, 4]

In [52]:
l = lambda x: x**2
l(4)

16

In [1]:
y = lambda x: x.split('@')[1]
y('taylor@com')

'com'